# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import auth_pb2 as auth__pb2
import bank_pb2 as bank__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x1a\nauth.proto\x1a\nbank.proto\"\x1d\n\rhealthRequest\x12\x0c\n\x04isUp\x18\x01 \x01(\x08\"\x1c\n\x0ehealthResponse\x12\n\n\x02up\x18\x01 \x01(\x08\"3\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"7\n\x13TransactionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf9\x01\n\x0eGatewayService\x12-\n\x0bProcessBank\x12\x0c.Transaction\x1a\x10.PaymentResponse\x12(\n\nGetBalance\x12\x08.Account\x1a\x10.BalanceResponse\x12\x36\n\x0fRegisterAccount\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12.\n\x0bHealthCheck\x12\x0e.healthRequest\x1a\x0f.healthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=41
  _globals['_HEALTHREQUEST']._serialized_end=70
  _globals['_HEALTHRESPONSE']._serialized_start=72
  _globals['_HEALTHRESPONSE']._serialized_end=100
  _globals['_PAYMENTRESPONSE']._serialized_start=102
  _globals['_PAYMENTRESPONSE']._serialized_end=153
  _globals['_TRANSACTIONRESPONSE']._serialized_start=155
  _globals['_TRANSACTIONRESPONSE']._serialized_end=210
  _globals['_GATEWAYSERVICE']._serialized_start=213
  _globals['_GATEWAYSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
