# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"`\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x16\n\x0einitial_amount\x18\x03 \x01(\x01\x12\x11\n\tbank_name\x18\x04 \x01(\t\";\n\x10RegisterResponse\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"E\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x11\n\tbank_name\x18\x03 \x01(\t\"E\n\rLoginResponse\x12\x16\n\x0e\x61\x63\x63ount_number\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2m\n\x0b\x41uthService\x12\x36\n\x0fRegisterAccount\x12\x10.RegisterRequest\x1a\x11.RegisterResponse\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=14
  _globals['_REGISTERREQUEST']._serialized_end=110
  _globals['_REGISTERRESPONSE']._serialized_start=112
  _globals['_REGISTERRESPONSE']._serialized_end=171
  _globals['_LOGINREQUEST']._serialized_start=173
  _globals['_LOGINREQUEST']._serialized_end=242
  _globals['_LOGINRESPONSE']._serialized_start=244
  _globals['_LOGINRESPONSE']._serialized_end=313
  _globals['_AUTHSERVICE']._serialized_start=315
  _globals['_AUTHSERVICE']._serialized_end=424
# @@protoc_insertion_point(module_scope)
