# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_files/bank.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto_files/bank.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto_files/bank.proto\"9\n\x07\x41\x63\x63ount\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x12\r\n\x05owner\x18\x03 \x01(\t\"V\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"%\n\x0fPrepareResponse\x12\x12\n\ncan_commit\x18\x01 \x01(\x08\"$\n\x11OperationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x0f\x42\x61lanceResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x01\x32\xb9\x01\n\x0b\x42\x61nkService\x12)\n\x07Prepare\x12\x0c.Transaction\x1a\x10.PrepareResponse\x12*\n\x06\x43ommit\x12\x0c.Transaction\x1a\x12.OperationResponse\x12)\n\x05\x41\x62ort\x12\x0c.Transaction\x1a\x12.OperationResponse\x12(\n\nGetBalance\x12\x08.Account\x1a\x10.BalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.bank_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNT']._serialized_start=26
  _globals['_ACCOUNT']._serialized_end=83
  _globals['_TRANSACTION']._serialized_start=85
  _globals['_TRANSACTION']._serialized_end=171
  _globals['_PREPARERESPONSE']._serialized_start=173
  _globals['_PREPARERESPONSE']._serialized_end=210
  _globals['_OPERATIONRESPONSE']._serialized_start=212
  _globals['_OPERATIONRESPONSE']._serialized_end=248
  _globals['_BALANCERESPONSE']._serialized_start=250
  _globals['_BALANCERESPONSE']._serialized_end=284
  _globals['_BANKSERVICE']._serialized_start=287
  _globals['_BANKSERVICE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
