# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto_files.auth_pb2 as auth__pb2
import proto_files.bank_pb2 as bank__pb2

# import proto_files.auth_pb2



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgateway.proto\x1a\nauth.proto\x1a\nbank.proto\"3\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2i\n\x0eGatewayService\x12-\n\x0bProcessBank\x12\x0c.Transaction\x1a\x10.PaymentResponse\x12(\n\nGetBalance\x12\x08.Account\x1a\x10.BalanceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTRESPONSE']._serialized_start=41
  _globals['_PAYMENTRESPONSE']._serialized_end=92
  _globals['_GATEWAYSERVICE']._serialized_start=94
  _globals['_GATEWAYSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
